# Generated by Django 5.1.1 on 2026-04-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexify", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nexifyannotation",
            name="type",
            field=models.CharField(
                choices=[
                    ("bbox", "Bounding Box"),
                    ("polygon", "Polygon"),
                    ("keypoint", "Keypoint"),
                    ("smart", "Smart Polygon (SAM)"),
                ],
                max_length=10,
            ),
        ),
    ]
