# Generated by Django 5.1.1 on 2026-05-01 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexify", "0002_alter_nexifyannotation_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nexifyworkspace",
            name="annotation_type",
            field=models.CharField(
                choices=[
                    ("bbox", "Bounding Box"),
                    ("polygon", "Manual Polygon"),
                    ("smart_polygon", "Smart Polygon (SAM)"),
                    ("keypoint", "Keypoint"),
                    ("all", "All Types"),
                ],
                default="bbox",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="nexifyworkspace",
            name="color",
            field=models.CharField(default="#667eea", max_length=7),
        ),
        migrations.AddField(
            model_name="nexifyworkspace",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
