# Generated by Django 5.2.13 on 2026-05-02 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexify", "0003_nexifyworkspace_annotation_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nexifyannotation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nexifyaugmentedimage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nexifydatasetversion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nexifyfolder",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nexifyimage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nexifyproject",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nexifyworkspace",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="nexifyassignment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="nexifydatasetversion",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="nexifyfolder",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="nexifylabelclass",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="nexifyannotation",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="nexifyannotation",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="nexifyannotation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="nexifyproject",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="nexifyworkspace",
            name="annotation_type",
        ),
        migrations.RemoveField(
            model_name="nexifyworkspace",
            name="color",
        ),
        migrations.AddField(
            model_name="nexifydatasetversion",
            name="export_file",
            field=models.FileField(blank=True, null=True, upload_to="nexify/exports/"),
        ),
        migrations.AddField(
            model_name="nexifydatasetversion",
            name="export_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="nexifydatasetversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="nexifydatasetversion",
            name="test_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nexifydatasetversion",
            name="train_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nexifydatasetversion",
            name="val_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nexifydatasetversion",
            name="zip_file",
            field=models.FileField(
                blank=True, null=True, upload_to="nexify/exports/zips/"
            ),
        ),
        migrations.AddField(
            model_name="nexifyfolder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="nexifyworkspace",
            name="max_images",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="nexifyworkspace",
            name="max_projects",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="nexifyworkspace",
            name="max_storage_mb",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name="nexifyworkspace",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("basic", "Basic"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nexifyannotation",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="nexifyannotation",
            name="label_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="nexify.nexifylabelclass",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nexifyannotation",
            name="type",
            field=models.CharField(
                choices=[
                    ("bbox", "Bounding Box"),
                    ("polygon", "Polygon"),
                    ("keypoint", "Keypoint"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nexifyassignment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nexify.nexifyproject"
            ),
        ),
        migrations.AlterField(
            model_name="nexifyassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("annotator", "Annotator"),
                    ("reviewer", "Reviewer"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nexifyassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="nexifyaugmentedimage",
            name="file",
            field=models.ImageField(upload_to="nexify/augmented/"),
        ),
        migrations.AlterField(
            model_name="nexifyaugmentedimage",
            name="original",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="augmented",
                to="nexify.nexifyimage",
            ),
        ),
        migrations.AlterField(
            model_name="nexifyaugmentedimage",
            name="transform_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="nexifydatasetversion",
            name="annotation_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nexifydatasetversion",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="nexifydatasetversion",
            name="format",
            field=models.CharField(
                choices=[
                    ("yolo", "YOLO"),
                    ("coco", "COCO"),
                    ("voc", "VOC"),
                    ("csv", "CSV"),
                    ("tensorflow", "TensorFlow"),
                    ("pytorch", "PyTorch"),
                    ("roboflow", "Roboflow"),
                    ("labelme", "LabelMe"),
                    ("kitti", "KITTI"),
                    ("json", "JSON"),
                    ("yaml", "YAML"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="nexifydatasetversion",
            name="image_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nexifydatasetversion",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nexify.nexifyproject"
            ),
        ),
        migrations.AlterField(
            model_name="nexifyimage",
            name="file",
            field=models.ImageField(upload_to="nexify/images/"),
        ),
        migrations.AlterField(
            model_name="nexifyimage",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nexifyimage",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="NexifyVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="nexify/videos/")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("duration_sec", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="nexify.nexifyfolder",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="nexifyassignment",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="nexifydatasetversion",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="nexifydatasetversion",
            name="notes",
        ),
    ]
