# Generated by Django 5.1.1 on 2026-05-03 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexify", "0004_alter_nexifyannotation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nexifyannotation",
            name="confidence",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="nexifyannotation",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="nexifyannotation",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="nexifyannotation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="nexifyassignment",
            name="assigned_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="nexifydatasetversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="nexifyfolder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="nexifyimage",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="nexifyproject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="nexifyworkspace",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="nexifyannotation",
            index=models.Index(
                fields=["image", "created_at"], name="nexify_nexi_image_i_58c1c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexifyannotation",
            index=models.Index(
                fields=["is_approved"], name="nexify_nexi_is_appr_4d92ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexifyassignment",
            index=models.Index(
                fields=["project", "status"], name="nexify_nexi_project_36afa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexifydatasetversion",
            index=models.Index(
                fields=["project", "status"], name="nexify_nexi_project_91fe73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexifyfolder",
            index=models.Index(
                fields=["project", "name"], name="nexify_nexi_project_f02eeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexifyimage",
            index=models.Index(
                fields=["folder", "uploaded_at"], name="nexify_nexi_folder__4b0e22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexifylabelclass",
            index=models.Index(
                fields=["project", "name"], name="nexify_nexi_project_5f8852_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexifyproject",
            index=models.Index(
                fields=["workspace", "created_at"],
                name="nexify_nexi_workspa_77a5eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nexifyworkspace",
            index=models.Index(
                fields=["owner", "created_at"], name="nexify_nexi_owner_i_8bba3b_idx"
            ),
        ),
    ]
