# Generated by Django 5.2.13 on 2026-05-03 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexify', '0005_nexifyannotation_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nexify_plan', models.CharField(choices=[('basic', 'Basic'), ('admin', 'Admin'), ('licensed', 'Licensed'), ('host', 'Host')], default='basic', max_length=20)),
                ('is_host', models.BooleanField(default=False)),
                ('email_approved', models.BooleanField(default=False)),
                ('rate_limit_annotations_per_hour', models.PositiveIntegerField(default=10)),
                ('rate_limit_uploads_per_hour', models.PositiveIntegerField(default=5)),
                ('rate_limit_projects_per_day', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nexify_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='nexify_user_user_id_36026a_idx')],
            },
        ),
    ]
