# Generated by Django 5.1.1 on 2026-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("annotation", "Annotation"),
                            ("automation", "Automation"),
                            ("sandbox", "Sandbox"),
                            ("spider", "Spider"),
                            ("wrangling", "Data Wrangling"),
                            ("sensor", "Sensor"),
                            ("camera", "Live Camera"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("status", models.CharField(default="idle", max_length=128)),
                ("info", models.JSONField(blank=True, default=dict)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-collected_at"],
            },
        ),
    ]
