# Generated by Django 5.1.1 on 2026-04-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = []
