# Generated by Django 5.1.1 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=512, unique=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("py", "Python"),
                            ("html", "HTML"),
                            ("index", "Index"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("components", models.CharField(blank=True, max_length=128)),
                ("line_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("is_dashboard_relevant", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-last_updated", "path"],
            },
        ),
    ]
