# Generated by Django 5.1.1 on 2024-12-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_sourcefile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("path", models.CharField(max_length=512)),
                ("model_type", models.CharField(default="yolo", max_length=64)),
                ("num_classes", models.IntegerField(default=0)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                ("accuracy", models.FloatField(default=0.0)),
                ("status", models.CharField(default="available", max_length=32)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-last_used", "-trained_at"],
            },
        ),
    ]