# Generated by Django 5.1.1 on 2026-04-23 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_auto_20260423_1523"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataset",
            name="project",
        ),
        migrations.RemoveField(
            model_name="image",
            name="project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="workspacemember",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="workspacemember",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="knowledgeentry",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="sourcefile",
            options={"ordering": ["-last_updated"]},
        ),
        migrations.AddField(
            model_name="feedbackmemory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="knowledge_type",
            field=models.CharField(
                choices=[
                    ("doc", "Documentation"),
                    ("script", "Script"),
                    ("config", "Configuration"),
                ],
                default="doc",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.sourcefile",
            ),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="is_dashboard_relevant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="is_knowledge_relevant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
        migrations.DeleteModel(
            name="Dataset",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Workspace",
        ),
        migrations.DeleteModel(
            name="WorkspaceMember",
        ),
    ]
