# Generated by Django 5.1.1 on 2026-04-03 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_modelweights"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcefile",
            name="is_knowledge_relevant",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("py", "Python"),
                    ("html", "HTML"),
                    ("index", "Index"),
                    ("other", "Other"),
                    ("script", "Script"),
                    ("doc", "Documentation"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "knowledge_type",
                    models.CharField(
                        choices=[("doc", "Documentation"), ("script", "Script")],
                        default="doc",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("content_preview", models.TextField(blank=True)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("consolidated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_entries",
                        to="dashboard.sourcefile",
                    ),
                ),
            ],
            options={
                "ordering": ["-consolidated_at"],
            },
        ),
    ]
