# Generated by Django 5.1.1 on 2026-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_clean_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="ollama-default", max_length=100)),
                ("model_name", models.CharField(default="llama3.2:1b", max_length=100)),
                (
                    "base_url",
                    models.CharField(default="http://localhost:11434", max_length=200),
                ),
                ("request_timeout", models.FloatField(default=120.0)),
                ("num_ctx", models.IntegerField(default=4096)),
                ("num_predict", models.IntegerField(default=512)),
                ("temperature", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
