# Generated by Django 5.2.13 on 2026-04-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial_annotation"),
        ("dashboard", "0004_sourcefile_is_knowledge_relevant_and_more"),
    ]

    operations = []
