# Generated by Django 5.1.1 on 2026-04-16 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_merge_20260414_1216"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("model_used", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(default="qwen2.5-coder:3b", max_length=100),
                ),
                (
                    "base_url",
                    models.CharField(default="http://localhost:11434", max_length=200),
                ),
                ("request_timeout", models.IntegerField(default=120)),
                ("num_ctx", models.IntegerField(default=4096)),
                ("num_predict", models.IntegerField(default=512)),
                ("temperature", models.FloatField(default=0.7)),
                ("top_p", models.FloatField(default=0.9)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RateLimitConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requests_per_minute", models.IntegerField(default=60)),
                ("requests_per_hour", models.IntegerField(default=1000)),
                ("concurrent_requests", models.IntegerField(default=5)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MetricRecord",
        ),
        migrations.DeleteModel(
            name="ModelWeights",
        ),
        migrations.AlterModelOptions(
            name="knowledgeentry",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sourcefile",
            options={},
        ),
        migrations.RenameField(
            model_name="knowledgeentry",
            old_name="consolidated_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="sourcefile",
            name="components",
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="vector_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="annotation",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="annotationtask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeentry",
            name="extracted_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="knowledgeentry",
            name="knowledge_type",
            field=models.CharField(default="code", max_length=50),
        ),
        migrations.AlterField(
            model_name="knowledgeentry",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.sourcefile",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeentry",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="file_type",
            field=models.CharField(default="other", max_length=20),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="is_dashboard_relevant",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="path",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
